DROP TABLE IF EXISTS PRODUCT;


CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  type VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  description TEXT DEFAULT NULL,
  remaining_qty INT NOT NULL
);